package com.atguigu.dao;

import com.atguigu.domain.Deptment;
import com.atguigu.domain.DeptmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_dept
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    int countByExample(DeptmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_dept
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    int deleteByExample(DeptmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_dept
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_dept
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    int insert(Deptment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_dept
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    int insertSelective(Deptment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_dept
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    List<Deptment> selectByExample(DeptmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_dept
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    Deptment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_dept
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Deptment record, @Param("example") DeptmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_dept
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    int updateByExample(@Param("record") Deptment record, @Param("example") DeptmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_dept
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    int updateByPrimaryKeySelective(Deptment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_dept
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    int updateByPrimaryKey(Deptment record);
}