package com.atguigu.domain;

public class Deptment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_dept.id
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_dept.name
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_dept.id
     *
     * @return the value of mybatis_dept.id
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_dept.id
     *
     * @param id the value for mybatis_dept.id
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_dept.name
     *
     * @return the value of mybatis_dept.name
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_dept.name
     *
     * @param name the value for mybatis_dept.name
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}