package com.atguigu.domain;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_test.id
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_test.last_name
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_test.email
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_test.gender
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_test.dept_id
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_test.id
     *
     * @return the value of mybatis_test.id
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_test.id
     *
     * @param id the value for mybatis_test.id
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_test.last_name
     *
     * @return the value of mybatis_test.last_name
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_test.last_name
     *
     * @param lastName the value for mybatis_test.last_name
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_test.email
     *
     * @return the value of mybatis_test.email
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_test.email
     *
     * @param email the value for mybatis_test.email
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_test.gender
     *
     * @return the value of mybatis_test.gender
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_test.gender
     *
     * @param gender the value for mybatis_test.gender
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_test.dept_id
     *
     * @return the value of mybatis_test.dept_id
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_test.dept_id
     *
     * @param deptId the value for mybatis_test.dept_id
     *
     * @mbggenerated Mon Aug 24 16:02:18 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}